### ISSUE TITLE
Feature request: Option to disable polling for updates, and/or make it manual

### ISSUE THREAD

**Issue by asveikau** [xyzroe/XZG#104]
**Is your feature request related to a problem? Please describe.**
Speaking personally I have a goal to minimize traffic to the external internet in my home devices.  I noticed that XZG has a periodic, default to 1am daily check for updates.  You can change the days and time but I didn't see a way to totally turn it off.

**Describe the solution you'd like**
An option to turn off checking for updates.
Perhaps also a button to manually check for updates, if you turn off the automatic check.

**Comment by SAOPP** [comment]
Perhaps in the future the ability to disable automatic checking for updates of XZG will be added.

**Comment by hexajon-art** [comment]
Is it working as intended? I've disabled update checks, but I still get notified of updates:

<img width="1072" height="1312" alt="Image" src="https://github.com/user-attachments/assets/a43ce0c1-cc7a-4f0a-b044-130b28b6243c" />
