### ISSUE TITLE
Feature request: the "old" firmware give the temperature of the device

### ISSUE THREAD

**Issue by alainvdu69** [xyzroe/XZG#106]
I've just flashed my ZigStarLanGW and i've noticed that there is no more the temperature of the device reported in Home Assistant

**Comment by SAOPP** [comment]
What sensor are we talking 'bout in this case? The coordinator temperature sensor transmitted via the mqtt?

**Comment by alainvdu69** [comment]
yes

**Comment by SAOPP** [comment]
But I don’t see such a sensor in ZigStar, can u be more specific what you’re talking about?

**Comment by SAOPP** [comment]
Here is all what I've in from my ZigStar GW POE:

![image](https://github.com/user-attachments/assets/9b22d85d-115c-4fa5-bba2-93bd38f27fc2)

What the sensor u're talking?

**Comment by alainvdu69** [comment]
in home assistant i have this :

sensor.cpu_temperature
ZigStarGW ESP Temperature
25.56

**Comment by alainvdu69** [comment]
well ... it's strange ... this sensor come back with the XZG

**Comment by alainvdu69** [comment]
so, i close ...

**Comment by alainvdu69** [comment]
didn't understand what happened ... the sensor come back on the device page in home assistant 1 day after the upgrade to XZG firmware ...
