### ISSUE TITLE
Little mistake in french translation on the status page

### ISSUE THREAD

**Issue by alainvdu69** [xyzroe/XZG#107]
The text displayed is : Révision du microLOGDciel

The right text should be : Révision du micrologiciel

My firmware is 2024.07.07

**Comment by SAOPP** [comment]
Hi!

U can contribute to the project development, make changes to the French language interface and make a merge request. :+1: 

https://github.com/xyzroe/XZG/blob/20240707/src/websrc/json/fr.json
