### ISSUE TITLE
Zigbee2mqtt and XZG-01

### ISSUE THREAD

**Issue by allseven** [xyzroe/XZG#123]
My zigbee2mqtt installation on HAOS with a XZG-01 coordinator has suddenly stopped working with zigbee2mqtt refusing to start.

I've gone back to a working backup of HA but that's not fixed it.

Hours of fiddling around has probably killed it off big time but do any of these screenshots offer any clues as to what the issue might be please?

As the HA backup restore hasn't fixed the problem, could my XZG-01 configuration the issue?

![Mosquitto broker config](https://github.com/user-attachments/assets/3847faea-088a-48df-9a74-77673ecba673)
![Mosquitto broker log](https://github.com/user-attachments/assets/1de1703e-4586-4875-b2d4-bced8669939f)
![XZG-01 mqtt config](https://github.com/user-attachments/assets/eff3ceab-9a50-4db2-849e-ebc058097ce0)
![XZG-01 network config](https://github.com/user-attachments/assets/aa6992a5-ebab-4d54-8c06-f218c9a70ce0)
![XZG-01 zigbee config](https://github.com/user-attachments/assets/64219f9c-a6bf-4f7c-8310-e8d8b7b52ed0)
![XZG-01](https://github.com/user-attachments/assets/2b89af60-7082-4f7a-ba2c-e252f103c270)
![zigbee2mqtt configuration](https://github.com/user-attachments/assets/97be5ade-4395-407d-8240-a3b93f9e2b06)
![zigbee2mqtt](https://github.com/user-attachments/assets/774e9634-ca20-4fb4-bc7b-ce3b915dac32)

**Comment by xyzroe** [comment]
on your screenshot USB mode is active, not LAN

**Comment by allseven** [comment]
Doh!! Thank you.I don't know how that got changed. 🤔🙄Best wishesFrank
-------- Original message --------From: xyzroe ***@***.***> Date: 05/11/2024  17:16  (GMT+00:00) To: xyzroe/XZG ***@***.***> Cc: allseven ***@***.***>, Author ***@***.***> Subject: Re: [xyzroe/XZG] Zigbee2mqtt and XZG-01 (Issue #123) 
on your screenshot USB mode is active, not LAN
