### ISSUE TITLE
Change button text from 'Sing in' to 'Sign in'

### ISSUE THREAD

**Issue by edmonddc** [xyzroe/XZG#18]
https://github.com/xyzroe/XZG/blob/f1fcad93fbf2504d858a4407a237f6f594fb1795/src/websrc/json/en.json#L263
![Screenshot 2024-05-24 at 07-38-42 Login - XZG](https://github.com/xyzroe/XZG/assets/25190569/ccb5dd3d-abf8-4eee-9afb-bfcb2f667640)

**Comment by xyzroe** [comment]
Thanks to @mercenaruss. He fixed this at 78be6f468342b959cabfe9a47941230cc23ec7ed
