### ISSUE TITLE
pfSense + HAProxy

### ISSUE THREAD

**Issue by willliamchan** [xyzroe/XZG#20]
I had my UZG01 just updated to the XZG firmware and found I am unable to connect to the Web UI using HAProxy.

Any idea please?

**Comment by xyzroe** [comment]
No I don't have any ideas how it could be connected to each other.
Maybe community have any ideas.

**Comment by SAOPP** [comment]
Need more details, too little information.

I don’t see any connection between updating the firmware and the inability to open the web interface using haproxy. Give more details about where the haproxy looks, and whether anything has changed on the gateway side.
