### ISSUE TITLE
Improve Font / Text Box coloring in Dark Mode

### ISSUE THREAD

**Issue by willliamchan** [xyzroe/XZG#21]
WiFi / VPN page in specific. Attached an example

![image](https://github.com/xyzroe/XZG/assets/54702221/3e63fe05-785e-44b8-9075-f19b9e5abed6)

**Comment by xyzroe** [comment]
If you enable switch color will change. 
But if you have any ideas how to improve - feel free to make a PR. 
CSS colors placed [here](https://github.com/xyzroe/XZG/blob/0473203b898953b492007d55027b97f2b8493223/src/websrc/css/custom.css#L401)
