### ISSUE TITLE
When DHCP is enabled, it is showing static IP and it's info.

### ISSUE THREAD

**Issue by willliamchan** [xyzroe/XZG#22]
So when I first upgrade the firmware and I am using Static IP, when I click to the IP setting page it is showing the default IP settings instead of what's being defined from previous firmware, I had mine switched from Static IP to DHCP and now IP info shows correctly.

**Comment by xyzroe** [comment]
Perhaps there is some bug with network setting migrating. 
I don't think there's much point in fixing this, given the large number of new features planned.

Thanks for the info. 
Sorry for the inconvenience.
