### ISSUE TITLE
No IP passed to MQTT

### ISSUE THREAD

**Issue by harvindhillon** [xyzroe/XZG#23]
In the previous firmware 0.26 and prior, MQTT configuration used to send the IP address of the coordinator

**To Reproduce**
1. Upgrade to XZG firmware
2. Enable MQTT Configuration

**Expected behavior**
IP Address as part of MQTT Payload

**Screenshots**
![image](https://github.com/xyzroe/XZG/assets/95908970/098c1308-fd20-47c7-af4d-a68a057fea55)
![image](https://github.com/xyzroe/XZG/assets/95908970/dcc9011b-58f1-407a-b0f2-df586dffa076)

**Additional context**

**Comment by xyzroe** [comment]
I have changed MQTT structure a little bit. See more info [here](https://xzg.xyzroe.cc/mqtt/)
You should have 2 new sensors after update: WLAN IP and LAN IP.

**Comment by harvindhillon** [comment]
Ah thanks, I see that what has happened is there are 2 devices now?
![image](https://github.com/xyzroe/XZG/assets/95908970/c8b355a1-4bed-4e1b-9e9e-20707009fb41)

and the new device has the new entities you mentioned, while the unchanged ones are still linked and updating to the old

![image](https://github.com/xyzroe/XZG/assets/95908970/c51c9ad3-ad2c-4c2f-a8f1-014beaf93a9c)


What should I do to merge them? Delete entities and restart?

**Comment by harvindhillon** [comment]
Ok thanks, deleted and restarted, that merged the devices.

**Comment by xyzroe** [comment]
I recommend to delete old device from HA. Or even both of them and then restart ESP32. 
It will generate new device will fully setup sensors.
