### ISSUE TITLE
Не прошивается Zigbee через Web после обновления  ESP32 до FW версия	20240519

### ISSUE THREAD

**Issue by alexps70** [xyzroe/XZG#24]
Пробовал несколько раз разные прошивки - процесс идет до 75-95% и после этого устройство полностью отваливается (и по ping в том числе). Принудительно передергиваю по питанию (POE) -  в окне статус "FW версия" либо пусто, либо 0
Пришлось прошивать через ZigStarGW-MT-x64
![Screenshot 2024-05-24 183837](https://github.com/xyzroe/XZG/assets/49348648/7307e5c7-0639-47e7-aa11-3353d2e59b8c)

**Comment by xyzroe** [comment]
We prefer to communicate in English on GitHub. 
If you want to use russian join our Telegram community. 

According to the problem you described:
Give a little bit more information - ESP32 HW and FW as well as Zigbee HW.
