### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by chrizy66** [xyzroe/XZG#30]
After update from 0.2.6 can't access web ui by fqdn; opening http://uzg-01/ redirects to 192.168.1.1 but my local address pool is in 10.0.0.0 range; Chrome, Firefox, Edge

**Comment by xyzroe** [comment]
Have you tried xzg.local ?

**Comment by chrizy66** [comment]
Tried:

http://uzg-01/, http://uzg-01.local/, http://uzg-01.home.arpa/ (my internal domain)

all leads to redirection to 192.168.1.1


If i try

http://xzg.local/, http://xzg.home.arpa/, http://xzg/

page not found.

**Comment by xyzroe** [comment]
Please try new release

**Comment by chrizy66** [comment]
Nothing changed on 20240525.1; still redirection to 192.168.1.1 after a while.
nslookup shows correct data:
Name:    uzg-01.home.arpa
Address:  10.xx.xx.19

**Comment by xyzroe** [comment]
@chrizy66  try now

**Comment by charrus** [comment]
This resolved DHCP address/DNS/mDNS/static

**Comment by chrizy66** [comment]
All is fine on the version 20240525.1.1
