### ISSUE TITLE
PoE powered UZG-01 does not come online after reboot

### ISSUE THREAD

**Issue by GD-Dal** [xyzroe/XZG#44]
Not sure if this is related to the switch or the UZG-01
If I restart the UZG-01, it does not come back until I shutdown the switchport and turn it back on.
Until then, the UZG network port blinks for a second, then goes dark. Blinks for a second then goes dark, etc.

The switch is a Cisco Catalyst 9300 of model C9300L-48UXG-4X
The port settings looks like this:
```
interface GigabitEthernet1/0/31
 description UZG
 switchport access vlan 1098
 switchport mode access
 device-tracking
 speed 100
```

The show power inline command shows this:

```
show power inline Gi1/0/31 detail 
 Interface: Gi1/0/31
 Inline Power Mode: auto
 Operational status: on
 Device Detected: yes
 Device Type: Ieee PD
 IEEE Class: 0
 Discovery mechanism used/configured: Ieee and Cisco
 Police: off

 Power Allocated 
 Admin Value: 60.0
 Power drawn from the source: 15.4
 Power available to the device: 15.4
 
 Actual consumption
 Measured at the port: 0.8
 Maximum Power drawn by the device since powered on: 0.9
 
 Absent Counter: 0
 Over Current Counter: 0
 Short Current Counter: 0
 Invalid Signature Counter: 0
 Power Denied Counter: 0

 Power Negotiation Used: None
 LLDP Power Negotiation --Sent to PD--      --Rcvd from PD--
   Power Type:          -                    -
   Power Source:        -                    -
   Power Priority:      -                    -
   Requested Power(W):  -                    -
   Allocated Power(W):  -                    -

Four-Pair PoE Supported: Yes
Spare Pair Power Enabled: No
Four-Pair PD Architecture: N/A
Perpetual POE Enabled: FALSE
Fast POE Enabled: FALSE
```

The configHW.json debug file contains this:

```
{
  "board": "UZG-01",
  "addr": 0,
  "pwrPin": -1,
  "mdcPin": 23,
  "mdiPin": 18,
  "phyType": 0,
  "clkMode": 3,
  "pwrAltPin": 5,
  "btnPin": 35,
  "btnPlr": 1,
  "uartSelPin": 33,
  "uartSelPlr": 1,
  "ledModePin": 12,
  "ledModePlr": 1,
  "ledPwrPin": 14,
  "ledPwrPlr": 1,
  "zbTxPin": 4,
  "zbRxPin": 36,
  "zbRstPin": 16,
  "zbBslPin": 32
}
```

**Comment by GD-Dal** [comment]
![image](https://github.com/xyzroe/XZG/assets/59178483/6d2b04e7-2a86-4d33-9f15-417730d42b2b)

I don't know how to open the box, though. It looks solid

**Comment by xyzroe** [comment]
Ok. No need. I'll check and come back.

**Comment by GD-Dal** [comment]
Didn't help at all.
But I discovered one thing though.

I turned of power on the switchport and powered up the UZG-01 via USB-cable instead.
And when I rebooted the UZG-01 some time later, the same thing happened.

The network port just blinked as before until I unplugged the usb cable, waited 10 seconds, and replugged it.

This is becoming the most unstable piece of hardware I have purchased for a long time.

Not possible to reboot without hassle
LQI is low on all zigbee devices.
Zigbee2MQTT crashes regularily because loss of connection

**Comment by NeoAcheron** [comment]
I am having similar problems with my UZG-01. Funny thing is that I updated the firmware two nights ago from 0.2.6, which was running for months without issues, but the new XZG firmware stays up for a few hours then dies, and basically my entire Zigbee network is down.

I'll be moving back to the old firmware while these issues are resolved.

**Comment by xyzroe** [comment]
> Didn't help at all. But I discovered one thing though.
> 
> I turned of power on the switchport and powered up the UZG-01 via USB-cable instead. And when I rebooted the UZG-01 some time later, the same thing happened.
> 
> The network port just blinked as before until I unplugged the usb cable, waited 10 seconds, and replugged it.
> 
> This is becoming the most unstable piece of hardware I have purchased for a long time.
> 
> Not possible to reboot without hassle LQI is low on all zigbee devices. Zigbee2MQTT crashes regularily because loss of connection

Let's separate Zigbee and ESP issues. 
Problem with LAN port is ESP issue. 
But low LQI as well as loss of Zigbee connection are Zigbee releated issues. Find more info in Zigbee firmware repository.

I will look for some solution to made ESP32 works with LAN port more stable.

**Comment by xyzroe** [comment]
> You could try to change `"pwrAltPin": 5,` to `"pwrAltPin": -1,` in your configHW.json

You could try to change "pwrAltPin": 5, to "pwrAltPin": -1, in your configHW.json. Have you?

**Comment by xyzroe** [comment]
> I have the same issue with UZG-01 (POE-0.4)

You could try to change "pwrAltPin": 5, to "pwrAltPin": -1, in your configHW.json. Have you?

**Comment by xyzroe** [comment]
@mercenaruss could you help us ?

**Comment by mercenaruss** [comment]
@tonius7570 @zoptooniek Try to change "pwrAltPin": -1, to "pwrAltPin": -1, in your configHW.json. 
If any of you have some time,please drop me an email support@zig-star.com and we will try remotely to debug this.

**Comment by xyzroe** [comment]
Could you try factory reset after updating to 20240607*

**Comment by xyzroe** [comment]
@zoptooniek could you check it later to confirm, and if no issues - close this issue ?
