### ISSUE TITLE
ZigBee FW revision after reboot is 0

### ISSUE THREAD

**Issue by stemer77** [xyzroe/XZG#47]
**Describe the bug**
After device reboot ZigBee FW revision on status page get "0" value.

**To Reproduce**
1. Restart whole device.
2. Check ZB FW revision

**Expected behavior**
ZigBee FW revision should be refreshed/checked.

**Screenshots**
![image](https://github.com/xyzroe/XZG/assets/74310093/31271f2e-8ab3-444e-9b59-5d8d516a915e)
I know, thats screenshot is from HA ;). And the unavailable status is my MQTT restart.

**Additional info**
When I press "Check Zigbee version" on Debug tools page, the firmware version is refreshed and get correct value.

**Comment by xyzroe** [comment]
Do you use original 20230507 or 460800 mod?

**Comment by stemer77** [comment]
I bought UZG-01 with this firmware version and never changed it.
