### ISSUE TITLE
502 Error on "General" page when using nginx proxy manager

### ISSUE THREAD

**Issue by maxandcheeses** [xyzroe/XZG#54]
**Describe the bug**
There is a 502 error when attempting to navigate to 'General' settings tab when going through a reverse proxy. In this case- I am using Nginx Proxy Manager.

**To Reproduce**
1. Setup reverse proxy that points to XZG device
2. Navigate to {xzg-device}.{your-domain}.com settings
3. Go to 'General' tab

**Expected behavior**
Page should load like all the other tabs

**Screenshots**
<img width="1792" alt="Screenshot 2024-05-29 at 3 36 04 PM" src="https://github.com/xyzroe/XZG/assets/164303325/41c0287b-87da-4bfd-80d3-597f5b6712d1">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - 125.0.6422.77

**Additional context**
All other tabs in the settings page loads just fine

**Comment by xyzroe** [comment]
I see 502 error on your screenshot

**Comment by maxandcheeses** [comment]
*corrected the mistake

**Comment by xyzroe** [comment]
I think the problem is caused by the header response with timezones names. It's large, about 8Kb. Check your nginx proxy for max headers size or so on.

**Comment by maxandcheeses** [comment]
You are spot on. I increase the size to address the issue.

```
proxy_buffers   4 32k;
proxy_buffer_size   32k;
```

Thanks for help!
