### ISSUE TITLE
tubeszb-efr32-mgm210-poe-2022 failed to load after flashing to XZG from ESPHome

### ISSUE THREAD

**Issue by 10Thirty** [xyzroe/XZG#77]
I flashed 20240612 via USB using the web flasher which seemed successful, however when I connected the ethernet back it powered up but was unreachable via the network and ZHA refused to connect. Re-flashed it with ESPHome and it came back up.

Here is  the [esp-web-tools-logs.txt](https://github.com/user-attachments/files/15810872/esp-web-tools-logs.txt)

this is the ESPHome .yaml [https://github.com/tube0013/tube_gateways/blob/850b7ff29925f1eaef1ef23fef872351e00f53b2/models/current/tubeszb-efr32-MGM210-poe/firmware/esphome/tubeszb-efr32-mgm210-poe-2022.yaml](https://github.com/tube0013/tube_gateways/blob/850b7ff29925f1eaef1ef23fef872351e00f53b2/models/current/tubeszb-efr32-MGM210-poe/firmware/esphome/tubeszb-efr32-mgm210-poe-2022.yaml)

Is this firmware meant to work with ESP devices connected to Silabs zigbee modules like the efr32 or is it only for Ti based ones?

**Comment by xyzroe** [comment]
For now only TI based devices supported

**Comment by 10Thirty** [comment]
Thought that might be the case, thanks for getting back to me.
