### ISSUE TITLE
Home Assistant - Update Notifications

### ISSUE THREAD

**Issue by ge33ek** [xyzroe/XZG#80]
**Is your feature request related to a problem? Please describe.**
A feature, it would be good if we had connectivity with Home Assistant that showed the available updates for the ESP32 and Zigbee firmware like all other HA components

**Describe the solution you'd like**
As above, the Zigstar UZG-01 reports its firmware position in HA

**Describe alternatives you've considered**
N/A - manually checking periodically if it is latest firmware.

**Additional context**
N/A

**Comment by xyzroe** [comment]
You can use MQTT, it must show ESP and Zigbee versions and two separate options for updates availability.
