### ISSUE TITLE
The Delete-button in File Browser is to easy to misinterpret

### ISSUE THREAD

**Issue by flemmingss** [xyzroe/XZG#82]
This delete button looks like magic wand to me.
And on top of that, it is not confirming deletion
![image](https://github.com/xyzroe/XZG/assets/25674067/8d02dec8-fa91-479e-abdf-591fd1b47d6a)

Request:

1. A better explanatory icon, and maybe a text
2. A popup to confirm deletion

**Comment by zappydood** [comment]
This just took down my entire zigbee network and I have no idea what is wrong with my slzb-06. It wont open the web panel, and I am having an extremely hard time finding out anything about anything. WHAT did I accidentally do!?

**Comment by flemmingss** [comment]
> This just took down my entire zigbee network and I have no idea what is wrong with my slzb-06. It wont open the web panel, and I am having an extremely hard time finding out anything about anything. WHAT did I accidentally do!?

Try a reboot of coordinator, worked for me.
