### ISSUE TITLE
Scan request failed or was not answered

### ISSUE THREAD

**Issue by dkrut** [xyzroe/XZG#83]
**Describe the bug**
I'm using HMG-01 POE Plus. It's cannot to add device via touchlink scan, because it returns an error.
Home Assistant OS 12.4, Zigbee2MQTT 1.38.0

**Device information**
- XZG:
![Status_page](https://github.com/xyzroe/XZG/assets/24831138/010fab1e-32fb-4b21-aa1f-a1a60f373b12)
![Zigbee_page](https://github.com/xyzroe/XZG/assets/24831138/c2e860e2-9781-4e95-b00d-9afd4bf1134f)

- params
`{
  "network-config": {
    "wifiEnbl": false,
    "wifiSsid": "",
    "wifiPass": "",
    "wifiDhcp": true,
    "wifiIp": "::",
    "wifiMask": "255.255.255.0",
    "wifiGate": "::",
    "wifiDns1": "1.1.1.1",
    "wifiDns2": "8.8.8.8",
    "wifiPwr": 78,
    "wifiMode": 1,
    "ethEnbl": true,
    "ethDhcp": true,
    "ethIp": "192.168.1.47",
    "ethMask": "255.255.255.0",
    "ethGate": "::",
    "ethDns1": "1.1.1.1",
    "ethDns2": "8.8.8.8"
  },
  "vpn-config": {
    "wgEnable": false,
    "wgLocalIP": "::",
    "wgLocalSubnet": "255.255.255.0",
    "wgLocalPort": 33333,
    "wgLocalGateway": "0.0.0.0",
    "wgLocalPrivKey": "",
    "wgEndAddr": "",
    "wgEndPubKey": "",
    "wgEndPort": 0,
    "wgAllowedIP": "0.0.0.0",
    "wgAllowedMask": "0.0.0.0",
    "wgMakeDefault": true,
    "wgPreSharedKey": "",
    "hnEnable": false,
    "hnJoinCode": "",
    "hnHostName": "XZG-8252",
    "hnDashUrl": "default"
  },
  "mqtt-config": {
    "enable": true,
    "server": "192.168.1.87",
    "port": 1883,
    "user": "mqtt",
    "pass": "mqtt",
    "topic": "XZG-8252",
    "updateInt": 60,
    "discovery": true,
    "reconnectInt": 15
  },
  "system-config": {
    "disableWeb": false,
    "webAuth": false,
    "webUser": "",
    "webPass": "",
    "fwEnabled": false,
    "fwIp": "0.0.0.0",
    "serialSpeed": 115200,
    "socketPort": 6638,
    "tempOffset": -4,
    "disableLedUSB": false,
    "disableLedPwr": false,
    "refreshLogs": 1,
    "hostname": "HMG-01",
    "timeZone": "Europe/Moscow",
    "ntpServ1": "pool.ntp.org",
    "ntpServ2": "time.google.com",
    "nightMode": false,
    "startHour": "23:00",
    "endHour": "07:00",
    "workMode": 0,
    "zbRole": 1,
    "zbFw": "?",
    "updHour": "00:00",
    "updDays": "*",
    "autoIns": false
  }
}`
  
**To Reproduce**
1. Open HomeAssistant
2. Open Zigbee2MQTT UI
3. Select Touchlink
4. Scan

**Expected behavior**
It found devices

**Actual behavior**
Errors:
> Info 2024-06-26 16:26:15Start Touchlink scan
> Info 2024-06-26 16:26:15Set InterPAN channel to '11'
> Warning 2024-06-26 16:26:15Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:15Set InterPAN channel to '15'
> Warning 2024-06-26 16:26:16Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:16Set InterPAN channel to '20'
> Warning 2024-06-26 16:26:16Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:16Set InterPAN channel to '25'
> Warning 2024-06-26 16:26:17Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:17Set InterPAN channel to '12'
> Warning 2024-06-26 16:26:17Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:17Set InterPAN channel to '13'
> Warning 2024-06-26 16:26:18Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:18Set InterPAN channel to '14'
> Warning 2024-06-26 16:26:18Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:18Set InterPAN channel to '16'
> Warning 2024-06-26 16:26:19Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:19Set InterPAN channel to '17'
> Warning 2024-06-26 16:26:19Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:19Set InterPAN channel to '18'
> Warning 2024-06-26 16:26:20Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:20Set InterPAN channel to '19'
> Warning 2024-06-26 16:26:20Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:20Set InterPAN channel to '21'
> Warning 2024-06-26 16:26:21Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:21Set InterPAN channel to '22'
> Warning 2024-06-26 16:26:21Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:21Set InterPAN channel to '23'
> Warning 2024-06-26 16:26:22Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:22Set InterPAN channel to '24'
> Warning 2024-06-26 16:26:22Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:23Set InterPAN channel to '26'
> Warning 2024-06-26 16:26:23Scan request failed or was not answered: 'Error: Timeout - null - 254 - null - 4096 - 1 after 500ms'
> Info 2024-06-26 16:26:23Restore InterPAN channel
> Info 2024-06-26 16:26:26Finished Touchlink scan
> Info 2024-06-26 16:26:26MQTT publish: topic 'zigbee2mqtt/bridge/response/touchlink/scan', payload '{"data":{"found":[]},"status":"ok","transaction":"9yw1f-1"}'

**Comment by xyzroe** [comment]
It is not related to XZG Firmware, cause all Zigbee processes are managed by Zigbee chip firmware and Zigbee Host Saftware (z2m/zha/etc)
