### ISSUE TITLE
Zigbee connected, but socket saying "No connection"

### ISSUE THREAD

**Issue by victorcpascua** [xyzroe/XZG#85]
**Describe the bug**
In my case Zigbee coordinator (via USB) was connected and working, but socket saying "No connection".

**Device information**
![Screenshot 2024-06-28 at 13 00 46](https://github.com/xyzroe/XZG/assets/39152749/5bd41d2d-693e-47d4-b591-a798d9c172d1)
![Screenshot 2024-06-28 at 13 00 37](https://github.com/xyzroe/XZG/assets/39152749/fd6e1ffe-7b39-40f6-a2c6-93dd95bf2749)

**Expected behavior**

**Screenshots**
![Screenshot 2024-06-28 at 12 58 47](https://github.com/xyzroe/XZG/assets/39152749/923673a8-511d-4200-a54e-6f5cbf519807)

**Additional context**
I want to monitorize via MQTT the zigbee network status.

**Comment by xyzroe** [comment]
But when using USB connection the socket is really disconnected, cause socket is network protocol.

Btw you can monitor you z2m status via MQTT on zigbee2mqtt/bridge/state
