### ISSUE TITLE
Ita translate error

### ISSUE THREAD

**Issue by kirkoff71** [xyzroe/XZG#91]
Are present error italian translate...
If do you want I can contribute.
Thanks

**Comment by kirkoff71** [comment]
Found and correct the "it.json"

**Comment by xyzroe** [comment]
Please make a PR with your contribution.

**Comment by kirkoff71** [comment]
Just made yesterday.
🙂

**Comment by xyzroe** [comment]
> Just made yesterday. 🙂

No. Please check twice. Every Italian will say Grazie to you.
<img width="1344" alt="Screenshot 2024-07-16 at 1 02 41 AM" src="https://github.com/user-attachments/assets/af45b324-9fd8-4a10-bb5c-685e775e83bf">
<img width="1321" alt="Screenshot 2024-07-16 at 1 02 45 AM" src="https://github.com/user-attachments/assets/d5de0639-6888-4c6a-a955-51a3316105dd">

**Comment by xyzroe** [comment]
I found you repository. You made new branch - super. Now you need to make pull request to push changes from your repository to this one.

**Comment by kirkoff71** [comment]
Now I make... check if is ok.
Thanks for your work :)

**Comment by xyzroe** [comment]
I still don't have any PRs

**Comment by xyzroe** [comment]
You have merged branch with main one but only in you repo. But you need just to open new pull request from you branch patch-1 to this repository main branch. If you open this repo main page in your browser GitHub will offer you to make a contribution using pull request.

**Comment by kirkoff71** [comment]
Now?
I attachment the file in this chat now
[it.json](https://github.com/user-attachments/files/16247318/it.json)

**Comment by xyzroe** [comment]
when you create a PR it will be visible not only to me or you, but to everyone. I believe you can do it.
