### ISSUE TITLE
uzg-01 zigstar wireguard vpn client  not working 

### ISSUE THREAD

**Issue by toloomierz** [xyzroe/XZG#92]
**Describe the bug**
wireguard not working over wifi 

**Device information**
Model	UZG-01
Firmware	20240707
Hardware	ESP32-D0WDQ6

Role	Coordinator
Firmware	20240710

**Comment by xyzroe** [comment]
Have you check that config over LAN ?

**Comment by toloomierz** [comment]
No only via wifi , and i watched tcpdump and there  was no traffic at all

**Comment by xyzroe** [comment]
Please make one more test but using wired connection to check your configuration.

**Comment by toloomierz** [comment]
I'll let U know

**Comment by toloomierz** [comment]
It's working via ethernet but wifi alone not

**Comment by toloomierz** [comment]
it works when i connect to vpn via eth and wifi on and  when i disconnect eth, connection over wifi  is still enabled and working , but wifi mode is changing from client to AP, as below 

 "Mode	AP
SSID	XZG-B1BB
DHCP	Enabled
IP	[172.16.2.111](http://172.16.2.111/)
Subnet	255.255.255.0 (Access point)
Gateway	192.168.1.1 (this device)
DNS	[172.16.1.101](http://172.16.1.101/)
RSSI	
noConn dBm
MAC	94:B9:7E:E2:27:9C"
when i reboot the device, the problem is back and no traffic is going through the wifi interface

**Comment by xyzroe** [comment]
Ok. Thanks for investigation. I'll try to fix it and let you know

**Comment by toloomierz** [comment]
thx.

**Comment by Oliviakrkk** [comment]
I guess this is the bug I was hitting when I reported #78 . I always tested using WIFI. 

I have the same problem.

**Comment by Oliviakrkk** [comment]
Is there a way to enable debug logs, check routing table or just check the initalization order? I wanted to check if wifi is connected first, then the wg.begin is called.

**Comment by Oliviakrkk** [comment]
Hi @xyzroe , 

Is there any test which I could do to help you solve this problem?

**Comment by xyzroe** [comment]
No, thanks. 
I need just some free time and motivation 😀
Someday it will happen.

**Comment by Oliviakrkk** [comment]
Today I did rollback to reenable zigbee network, as I really need my humidity monitoring back :-).  The new guide how to configure it helped. 

Looks like the last working version is `20240531` and it stopped working in `20240602`. 

https://github.com/xyzroe/XZG/compare/20240531...20240602

**Comment by toloomierz** [comment]
@Oliviakrkk , thx for info, I'll do the rollback to 20240531

**Comment by toloomierz** [comment]
is this bug solved yet ???

**Comment by Oliviakrkk** [comment]
@toloomierz on which firmware? I installed `20240914` and are unable to connect.
